services:
  web:
    image: node:18
    working_dir: /app
    volumes:
      - /home/jimmy/Alsoadaa:/app
    ports:
      - "3847:5173"
    restart: unless-stopped
    container_name: alsoadaa-website
    command: >
      bash -c "
      npm install --include=dev &&
      npm run build &&
      npx vite preview --host 0.0.0.0 --port 5173 --strictPort
      "
    environment:
      - NODE_ENV=production
